name: Build iOS Binaries

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout ffmpeg-kit
      uses: actions/checkout@v4
      with:
        repository: JeffreyCA/ffmpeg-kit
        path: ffmpeg-kit-src

    - name: Install dependencies
      run: |
        brew install autoconf automake libtool pkg-config curl cmake gcc gperf texinfo yasm nasm bison autogen git wget meson ninja tree

    - name: Build iOS binaries
      run: |
        cd ffmpeg-kit-src
        ./ios.sh --disable-armv7 --disable-armv7s --disable-i386 --disable-x86-64

    - name: Copy iOS binaries
      run: cp -r ffmpeg-kit-src/prebuilt/apple-ios-arm64/* .

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Check in iOS binaries"
        git push
